allow_fail:
- env: BUILDVARIANT=raspberry.armhf
- env: BUILDVARIANT=ubuntu.i686.gles
- env: BUILDVARIANT=ubuntu.i686.gles2
- env: BUILDVARIANT=android.x86.kitkat
- env: BUILDVARIANT=android.x86_64.nougat
- env: BUILDVARIANT=ios
- env: BUILDVARIANT=steam.amd64
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
coverage: false
display_name: Coffee Dependencies
makefile_location: toolchain/makers
name: CoffeeDependencies
platforms:
  android:
    armv7a:
    - nougat
    - lollipop
    - kitkat
    armv8a:
    - nougat
    - lollipop
    x86:
    - kitkat
    x86_64:
    - nougat
  emscripten:
  - wasm
  fedora:
  - amd64
  ios:
  - .
  - x86_64
  mingw:
  - .
  osx:
  - .
  raspberry:
  - armhf
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  uwp:
  - amd64
  win32:
  - amd64
  - x86
script_location: toolchain/ci
template_location: toolchain/cmake/Templates
version:
  hotfix: 1
  major: 0
  minor: 3
  patch: 3
  release: 2
versionprefix: rel-
