before_build:
- ps: toolchain\ci\appveyor-build.ps1
before_deploy:
- cmd: cmake.exe --build %BUILD_DIR% --target install --config %CONFIGURATION%
branches:
  only:
  - master
  - testing
build:
  parallel: true
  project: Dependencies.sln
  verbosity: minimal
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git
    %SOURCE_DIR%
- cmd: cd %SOURCE_DIR% && git checkout -qf %APPVEYOR_REPO_COMMIT%
configuration:
- Debug
deploy_script:
- ps: toolchain\ci\appveyor-deploy.ps1
environment:
  BUILD_DIR: C:\projects\%APPVEYOR_PROJECT_SLUG%
  CMAKE_BIN: cmake.exe
  DEPENDENCIES: ''
  DEPLOY_PATTERNS: ''
  GITHUB_TOKEN:
    secure: ''
  MAKEFILE_DIR: toolchain\makers
  NOBUILD: 1
  SAME_BUILD_DIR: 1
  SOURCE_DIR: C:\projects\%APPVEYOR_PROJECT_SLUG%\src
  matrix:
  - BUILDVARIANT: uwp.amd64
  - BUILDVARIANT: win32.amd64
  - BUILDVARIANT: win32.x86
image:
- Visual Studio 2015
- Visual Studio 2017
install:
- ps: toolchain\ci\appveyor-deps.ps1
matrix:
  allow_failures: []
  exclude:
  - BUILDVARIANT: uwp.amd64
    image: Visual Studio 2015
platform: x64
skip_tags: true
version: '{build}'
